#!/usr/bin/env sh

echo -e "\033[32mRunning commit-msg hook"
commit="$(cat $1)"
branch=$(git rev-parse --abbrev-ref HEAD)
kind=$(echo $branch | cut -d '/' -f1)
echo $kind

labels="feature=[FEAT] bugfix=[BUGFIX] hotfix=[HOTFIX] release=[RELEASE] docs=[DOCS] test=[TEST] refactor=[REFACTOR] style=[CI] wip=[WIP] main=[MAIN] master=[MAIN]"

label=""
for entry in $labels; do
    prefix=$(echo $entry | cut -d '=' -f1)
    value=$(echo $entry | cut -d '=' -f2)
    if [[ "$branch" == "$prefix"* ]]; then
        label=$value
        break
    fi
done

if [ -n "$label" ]; then
    echo -e "\033[32m$(echo ${kind:0:1} | tr '[:lower:]' '[:upper:]')${kind:1} branch"
    echo "$label - $commit" > "$1"
    exit 0
else
    echo -e "\033[31mInvalid branch name"
    exit 1
fi
