version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - webnet
    command:
      - sh
      - -c
      - |
        yarn install
        yarn start:dev
    environment:
      DOCKER: 'true'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
      POSTGRES_USERNAME: postgres
    networks:
      - webnet
    ports:
      - '5432:5432'
volumes:
  dbdata: {}
networks:
  webnet:
    driver: bridge
