apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.mdb.dev.yml -o deploy
    kompose.version: 1.28.0 (HEAD)
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.mdb.dev.yml -o deploy
        kompose.version: 1.28.0 (HEAD)
      labels:
        io.kompose.network/uprater-webnet: "true"
        io.kompose.service: node
    spec:
      containers:
        - env:
            - name: DOCKER
              value: "true"
            - name: STAGE
              value: k8
            - name: MONGO_URI
              value: mongodb://mongo-0.mongo.default.svc.cluster.local:27017,mongo-1.mongo.default.svc.cluster.local:27017,mongo-2.mongo.default.svc.cluster.local:27017/uprater?replicaSet=rs0
            - name: DB_HOST_1
              value: mongo1
            - name: DB_HOST_2
              value: mongo2
            - name: DB_HOST_3
              value: mongo3
            - name: DB_PORT
              value: "27017"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_DATABASE
              value: uprater
            - name: JWT_SECRET
              value: bVT8gpxLvd2P(!{wwyAe:[Q@UF(LYev(
            - name: COHERE_API_KEY
              value: B3yFEFh14ZrzFoFDBMy6rEFKzBrSsP4qEPQXeSQN
            - name: WAIT_HOSTS
              value: mongo1:27017
          image: eneko2496/main_server:latest
          name: node
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: node-claim0
            - mountPath: /app/node_modules
              name: node-claim1
      restartPolicy: Always
      volumes:
        - name: node-claim0
          persistentVolumeClaim:
            claimName: node-claim0
        - name: node-claim1
          persistentVolumeClaim:
            claimName: node-claim1
status: {}