apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
    io.kompose.service: rabbit
  name: rabbit
spec:
  selector:
    io.kompose.service: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
        io.kompose.network/uprater-webnet: "true"
        io.kompose.service: rabbit
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: mypassword
        - name: RABBITMQ_DEFAULT_USER
          value: user
        - name: RABBITMQ_NODE_PORT
          value: "5672"
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
