apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
data:
  migrate_data_users.json: |-
    [
      {
        "_id": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "email": "imoreno.main@gmail.com",
        "password": "$2b$10$UvufS2irHQjpeAl0GIHV9.x60iU5US7777Gf8FilFbi.mtxxuKVnS",
        "__v": 0
      },
      {
        "_id": {
          "$oid": "64406a6ccaa7623abab719e7"
        },
        "email": "imoreno@gmail.com",
        "password": "$2b$10$ZOYRwt8epen/R23ppRQWNeAs4TQqLJYwVzqhE4Ya1VtAud0a5JRg2",
        "__v": 0
      }
    ]
  migrate_data_rates.json: |-
    [
      {
        "comment": "I loved their new album, it's so good!",
        "topics": [
          "music"
        ],
        "value": 9,
        "created_at": "2022-03-15T10:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their latest movie was terrible, I wouldn't recommend it to anyone.",
        "topics": [
          "movies"
        ],
        "value": 2,
        "created_at": "2022-03-16T15:45:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their political views are very problematic, I can't support them.",
        "topics": [
          "politics"
        ],
        "value": 3,
        "created_at": "2022-03-17T08:20:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their cooking skills are amazing, I've never had a better meal!",
        "topics": [
          "food"
        ],
        "value": 10,
        "created_at": "2022-03-18T12:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I saw them at a sports game last weekend, they were really into it!",
        "topics": [
          "sports"
        ],
        "value": 7,
        "created_at": "2022-03-19T19:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their religious beliefs are different from mine, but I respect their choices.",
        "topics": [
          "religion"
        ],
        "value": 5,
        "created_at": "2022-03-20T11:15:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "They have some amazing travel stories, I love hearing about their adventures!",
        "topics": [
          "travel"
        ],
        "value": 8,
        "created_at": "2022-03-21T16:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I always have a great time hanging out with them, they're so fun!",
        "topics": [
          "leisure"
        ],
        "value": 9,
        "created_at": "2022-03-22T21:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I don't like their taste in music, it's just not for me.",
        "topics": [
          "music"
        ],
        "value": 4,
        "created_at": "2022-03-23T14:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their street style",
        "topics": [
          "street"
        ],
        "value": 7,
        "created_at": "2022-03-24T09:45:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I don't agree with their political views, but I can appreciate their passion.",
        "topics": [
          "politics"
        ],
        "value": 6,
        "created_at": "2022-03-25T18:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their taste in movies is great, they always recommend the best ones!",
        "topics": [
          "movies"
        ],
        "value": 8,
        "created_at": "2022-03-26T11:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I've never seen someone as passionate about their favorite sports team as they are!",
        "topics": [
          "sports"
        ],
        "value": 9,
        "created_at": "2022-03-27T16:15:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their cooking skills are just average, nothing special.",
        "topics": [
          "food"
        ],
        "value": 5,
        "created_at": "2022-03-28T08:45:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I don't really care about their religious beliefs, it's not my business.",
        "topics": [
          "religion"
        ],
        "value": 7,
        "created_at": "2022-03-29T13:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their travel photos always make me jealous, they go to such amazing places!",
        "topics": [
          "travel"
        ],
        "value": 9,
        "created_at": "2022-03-30T20:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I love their taste in music, we always jam together!",
        "topics": [
          "music"
        ],
        "value": 8,
        "created_at": "2022-04-01T14:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "They always find the best spots to hang out and have fun.",
        "topics": [
          "leisure"
        ],
        "value": 9,
        "created_at": "2022-04-02T19:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their political views are just so extreme, it's hard to have a conversation with them.",
        "topics": [
          "politics"
        ],
        "value": 3,
        "created_at": "2022-04-03T09:15:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their food always looks so delicious, I wish I could taste it!",
        "topics": [
          "food"
        ],
        "value": 8,
        "created_at": "2022-04-04T17:30:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I love talking to them about travel, they have such interesting stories!",
        "topics": [
          "travel"
        ],
        "value": 7,
        "created_at": "2022-04-05T11:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their taste in movies is just not my cup of tea, but to each their own!",
        "topics": [
          "movies"
        ],
        "value": 5,
        "created_at": "2022-04-06T15:45:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "Their religious beliefs are really important to them, and that's great.",
        "topics": [
          "religion"
        ],
        "value": 8,
        "created_at": "2022-04-07T07:15:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      },
      {
        "comment": "I'm not really into sports, but they always make it look like so much fun!",
        "topics": [
          "sports"
        ],
        "value": 7,
        "created_at": "2022-04-08T12:00:00Z",
        "comment_count": 0,
        "reactions_count": 0,
        "weight": 1,
        "user_from": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "user_to": {
          "$oid": "64406a6ccaa7623abab719e7"
        }
      }
    ]
  migrate_data_profiles.json: |-
    [
      {
        "_id": {
          "$oid": "64406a66caa7623abab719e5"
        },
        "username": "Hacker",
        "city": "Barcelona",
        "age": 23,
        "c_rates": 0,
        "__v": 0
      },
      {
        "_id": {
          "$oid": "64406a6ccaa7623abab719e7"
        },
        "username": "Enekinho",
        "city": "Barcelona",
        "age": 23,
        "c_rates": 0,
        "__v": 0
      }
    ]
  migrate.sh: |-
    #!/bin/bash
    echo "Migrating data..."
    mongoimport --host mongodb --db mydb --collection users --file /scripts/migrate_data_users.json
    mongoimport --host mongodb --db mydb --collection rates --file /scripts/migrate_data_rates.json
    mongoimport --host mongodb --db mydb --collection profiles --file /scripts/migrate_data_profiles.json
