export enum Topics {
  POLITICS = 'politics',
  RELIGION = 'religion',
  SPORTS = 'sports',
  MOVIES = 'movies',
  MUSIC = 'music',
  FOOD = 'food',
  TRAVEL = 'travel',
  // 'books',
  // 'tv',
  // 'art',
  // 'science',
  // 'history',
  // 'technology',
  // 'gaming',
  // 'fashion',
  // 'pets',
  // 'cars',
  // 'finance',
  // 'fitness',
  // 'health',
  // 'relationships',
  // 'parenting',
  // 'education',
  // 'career',
  // 'hobbies',
  // 'other',
}

export enum Reactions {
  LIKE = 'like',
  DISLIKE = 'dislike',
  // 'love',
  // 'hate',
  // 'laugh',
  // 'cry',
  // 'angry',
  // 'sad',
  // 'happy',
  // 'confused',
  // 'surprised',
  // 'other',
}
