apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.mdb.dev.yml -o deploy
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  type: NodePort
  ports:
    - name: "5173"
      port: 5173
      targetPort: 5173
      nodePort: 30080
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}