name: Docker Image CI

on:
  pull_request:
    types:
      - "closed"
    branches: [ main ]
  push:
    branches: [ features/test-init ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p {{ secrets.REGISTRY_PASSWORD }} https://hub.docker.com


    - name: Build and push node container
      run: |
        cd main_server
        docker build -t node:$(date +%s) .
        docker push node:$(date +%s)

    - name: Build and push cohere container
      run: |
        cd cohere_ms
        docker build -t cohere-ms:$(date +%s) .
        docker push cohere-ms:$(date +%s)

    - name: Build and push ui container
      run: |
        cd web_app_uprater
        docker build -t ui:$(date +%s) .
        docker push ui:$(date +%s)
