name: Docker Image CI

on:
  pull_request:
    types:
      - "closed"
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    - name: Build node container
      working-directory: ./main_server
      run:  docker build -t node:latest .

    - name: Push node container
      working-directory: ./main_server
      run: docker push node:latest

    - name: Build and push cohere container
      run: |
        cd cohere_ms
        docker build -t cohere-ms:latest .
        docker push cohere-ms:latest

    - name: Build and push ui container
      run: |
        cd web_app_uprater
        docker build -t ui:latest .
        docker push ui:latest
