name: Docker Image CI

on:
  pull_request:
    types:
      - "closed"
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: https://index.docker.io/v1/ 
    - name: Extract metadata (tags, labels) for Docker main_server
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: eneko2496/node:latest

    - name: Build and push Docker image main_server
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./main_server
        push: true
        tags: eneko2496/node:latest
        labels: |
          com.example.build-date=${{ github.event.head_commit.timestamp }}
          
    - name: Extract metadata (tags, labels) for Docker cohere
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: eneko2496/cohere-ms:latest

    - name: Build and push Docker image cohere
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./cohere_ms
        push: true
        tags: eneko2496/cohere-ms:latest
        labels: |
          com.example.build-date=${{ github.event.head_commit.timestamp }}

    - name: Extract metadata (tags, labels) for Docker ui
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: eneko2496/ui:latest

    - name: Build and push Docker image ui
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./web_app_uprater
        push: true
        tags: eneko2496/ui:latest
        labels: |
          com.example.build-date=${{ github.event.head_commit.timestamp }}
