name: MongoDB Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MongoDB
      uses: docker/setup-mongodb@v1
      with:
        mongodb-version: '4.4'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run migrations
      run: npm run migrate

    - name: Run tests
      run: npm run test
