name: MongoDB Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "4.4"
          mongodb-replica-set: rs0
          mongodb-port: 27017

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to main_server directory
        run: cd main_server
   
      - name: Create .env.stage.test
        run: |
          echo "pwd $(ls)"
          cd main_server
          echo "MONGO_URI=mongodb://localhost:27017" >> .env.stage.test
          echo "DB_DATABASE=uprater" >> .env.stage.test
          echo "JWT_SECRET=bVT8gpxLvd2P(!{wwyAe:[Q@UF(LYev(" >> .env.stage.test

      - name: Install dependencies
        working-directory: ./main_server
        run: npm i -E

      - name: Install MongoDB tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.6.1.deb
          sudo dpkg -i mongodb-database-tools-ubuntu2004-x86_64-100.6.1.deb

      - name: Run migrations
        working-directory: ./main_server
        run: npm run migrate

      - name: Run server 
        working-directory: ./main_server
        run: npm run start:test & 
      
      - name: debug
        run: |
          echo "Checking if Node.js server is running..."
          sleep 10
          curl http://localhost:3000

      - name: Wait for Node instance to be running
        run: |
          sleep 10
          echo "wait for node instance to be open"
          npx wait-on http://localhost:3000

      - name: Run tests
        working-directory: ./main_server
        run: npm run test
