name: MongoDB Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '4.4'
        mongodb-replica-set: rs0
        mongodb-port: 27017

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run migrations
      run: npm run migrate

    - name: Run tests
      run: npm run test
