name: MongoDB Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "4.4"
          mongodb-replica-set: rs0
          mongodb-port: 27017

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to main_server directory
        run: cd main_server

      - name: Install dependencies
        working-directory: ./main_server
        run: npm ci

      - name: Run migrations
        working-directory: ./main_server
        run: npm run migrate

      - name: Run tests
        working-directory: ./main_server
        run: npm run test
